#!/bin/bash
# Check folder (ignore case)
if [ "$(basename "$PWD" | tr '[:upper:]' '[:lower:]')" != "password-generator" ]; then
    echo "Error: You must run this program from the 'password-generator' folder!"
    exit 1
fi

python3 password_generator.py "$@"
